-- AlterTable
ALTER TABLE "transaction_row" ADD COLUMN     "boxH" DOUBLE PRECISION,
ADD COLUMN     "boxW" DOUBLE PRECISION,
ADD COLUMN     "boxX" DOUBLE PRECISION,
ADD COLUMN     "boxY" DOUBLE PRECISION;
